### ISSUE TITLE
Un-defined variable should be undefined

### ISSUE THREAD

**Issue by duyet** [IonicaBizau/is-undefined#1]
Un-defined variable should be undefined, and return `true`.

How about if I have: 

``` js
const isUndefined = require("is-undefined");

isUndefined('hello'); // false
isUndefined(duyetdev); // Uncaught ReferenceError: c is not defined
```

Let's discuss :smile_cat:

**Comment by IonicaBizau** [comment]
Hope that is not `undefined`. :joy: 
For checking that you really need `typeof duyetdev === "undefined"`. :grin: 

In your case the error will be `Uncaught ReferenceError: duyetdev is not defined`, tho.

**Comment by duyet** [comment]
I already check before create an issue :smile: 
`typeof duyetdev === "undefined"` is `true`. But `isUndefined(duyetdev)` will throw an error. 
You can quick check in chrome: 

![screenshot from 2016-02-17 23-58-48](https://cloud.githubusercontent.com/assets/5009534/13117539/ef6fdd42-d5d2-11e5-8964-c4fa6bb8367a.png)

**Comment by IonicaBizau** [comment]
@duyetdev Yes, that's obvious: you're passing a variable which is not defined to a function. :smile:

**Comment by duyet** [comment]
You say I'm passing a not defined variable. Thus, the `is-undefined` function should be return **true**, because that is its features, right :smile:

**Comment by IonicaBizau** [comment]
@duyetdev Nope, `is-undefined` returns `true` if the value you pass is `undefined`. :laughing:

**Comment by IonicaBizau** [comment]
But `duyetdev` is not `undefined`. And the error doesn't come from my library, so it's not a bug. :stuck_out_tongue:

**Comment by duyet** [comment]
:+1: I know the input is `undefined`, so what reason do I use this library haha :smile:

**Comment by IonicaBizau** [comment]
Sometimes you don't know if a value is `undefined` or not, so you definitely need to use this library for checking that. :joy:

**Comment by duyet** [comment]
Yes, in this case I don't know `duyetdev`'s value is `undefined` or not. So I using your library :sob:

**Comment by IonicaBizau** [comment]
@duyetdev Because you didn't define `duyetdev`. :smile: 

`undefined` vs a variable that is not defined:

> What is your `name`?
> 
> What?! What is a `name`? I don't know what a `name` is. `name` was not defined.
> 
> `name = undefined`
> 
> What is your name?
> 
> I don't have a name. (`=> undefined`)

:grin:
